### ISSUE TITLE
Arduino incompatibility, fix suggestion

### ISSUE THREAD

**Issue by ASL07** [buelowp/sunset#14]
Hi, 
Thanks for the great library
I just tried to compile this inside a PlatformIO Arduino project, and I got a compilation error because Arduino redefines min and max macros

Adding this fixes the problem. I wonder if you would like to add it to the repo, or maybe there is a better way to do it

```
#undef min
#undef max

#include <math.h>
#include <time.h>
#include <chrono>
```

**Comment by buelowp** [comment]
Let me look into this. Can you give me the real compiler error output? Honestly, this should have come up before, EVERY platform defines these. Also, It doesn't seem to be a problem with the Arduino IDE, so I would like to look into this more before I commit any change. I have a lot of other users who depend on this and breaking their environment isn't a good way to go about it.

**Comment by ASL07** [comment]
This is the first of the hundresds of errors the compiler gives me. I am not usnig the Arduino IDE, I am using Platform IO.
I would not be surprised if it is a Platformio issue, it does lots of strange things

```
In file included from test/samd21/sunset_samd21_tests.cpp:4:0:
src/sunset.h:36:8: warning: extra tokens at end of #endif directive [-Wendif-labels]
 #endif min
        ^~~
In file included from /Users/developer/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/7.2.1/chrono:40:0,
                 from src/sunset.h:41,
                 from test/samd21/sunset_samd21_tests.cpp:4:
/Users/developer/.platformio/packages/toolchain-gccarmnoneeabi/arm-none-eabi/include/c++/7.2.1/limits:321:11: error: macro "max" requires 2 arguments, but only 1 given
       max() _GLIBCXX_USE_NOEXCEPT { return _Tp(); }
           ^
```

**Comment by buelowp** [comment]
I have not tried to compile on PIO, nor do I expect to, but send me the complete dump. I'm interested in seeing what it says. I do have PIO, but not setup for Arduino, so I'll let you know if I can do it.

**Comment by ASL07** [comment]
I have created a new repo so you can reproduce it. The compilation output is more than 1000 lines so i won't post it here
If you have platformio installed, just download it and compile using the command **platformio run** on the root folder of the repo
https://github.com/ASL07/sunset-14
Thanks

**Comment by buelowp** [comment]
I finally figured out what the issue was. There was a bad string in the src/sunset.h file, which is now fixed. The 1.0.10 version should work for you now. It has nothing to do with the min/max macros.

**Comment by ASL07** [comment]
I see, didn't realize about that, will retest and update this issue
Thanks!

**Comment by ASL07** [comment]
Hi @buelowp . I have retested and it is still happening.
Actually I was not using sunset.h before, I modified the cpp file to include SunSet.h directly

It might not happen for other Arduino cores, as they don't redefine these macros, but the SamD core defines them here
https://github.com/arduino/ArduinoCore-samd/blob/master/cores/arduino/Arduino.h

**Comment by buelowp** [comment]
OK, I think I found the problem. The SAMD compiler isn't C++ friendly for std::chrono which seems to have been causing the issues. I am pushing a change to update the code. I'm dropping std::chrono which fixes this for me on PIO for SAMD, and I'm going to update the includes to be more C++ friendly.

**Comment by ASL07** [comment]
I think the problem lies in Arduino core itself, not in your library, but I thought it could be fixed in the library as it is not too difficult.

I have opened an issue in the Arduino core repo

**Comment by buelowp** [comment]
I somewhat disagree. I was able to reproduce your issue, and fix it with the patch I just committed. Yes, their implementation may have issues with C++, but it should be resolved now.

**Comment by buelowp** [comment]
Closing due to inactivity
